export const TAX_STATUS_LIST = [
  { value: '01', label: 'Individual' },
  // { value: '02', label: 'On behalf of minor' },
  // { value: '03', label: 'HUF' },
  // { value: '04', label: 'Company' },
  // { value: '13', label: 'Sole Proprietorship' },
  // { value: '21', label: 'NRE' },
  // { value: '24', label: 'NRO' },
  // { value: '26', label: 'NRI - MINOR' },
  // { value: '27', label: 'NRI - HUF' }
];

export const HOLDING_PATTERN_LIST = [
  { value: 'SI', label: 'Single' },
  { value: 'JO', label: 'Joint' },
  { value: 'AS', label: 'Anyone or Survivor' }
];

export const KYC_TYPE_OPTIONS = [
  { key: 'B', value: 'BIOMETRIC KYC' },
  // { key: 'C', value: 'CKYC Compliant' },
  { key: 'E', value: 'Aadhhaar EKYC PAN' },
  { key: 'K', value: 'KRA Compliant' }
];

export const STATE_LIST = [
  { key: 'AN', value: 'Andaman & Nicobar' },
  { key: 'AR', value: 'ArunachalPradesh' },
  { key: 'AP', value: 'Andhra Pradesh' },
  { key: 'AS', value: 'Assam' },
  { key: 'BH', value: 'Bihar' },
  { key: 'CH', value: 'Chandigarh' },
  { key: 'CG', value: 'Chhattisgarh' },
  { key: 'DL', value: 'Delhi' },
  { key: 'GO', value: 'GOA' },
  { key: 'GU', value: 'Gujarat' },
  { key: 'HA', value: 'Haryana' },
  { key: 'HP', value: 'Himachal Pradesh' },
  { key: 'JM', value: 'Jammu & Kashmir' },
  { key: 'JK', value: 'Jharkhand' },
  { key: 'KA', value: 'Karnataka' },
  { key: 'KE', value: 'Kerala' },
  { key: 'MP', value: 'Madhya Pradesh' },
  { key: 'MA', value: 'Maharashtra' },
  { key: 'MN', value: 'Manipur' },
  { key: 'ME', value: 'Meghalaya' },
  { key: 'MI', value: 'Mizoram' },
  { key: 'NA', value: 'Nagaland' },
  { key: 'ND', value: 'New Delhi' },
  { key: 'OR', value: 'Odisha' },
  { key: 'PO', value: 'Pondicherry' },
  { key: 'PU', value: 'Punjab' },
  { key: 'RA', value: 'Rajasthan' },
  { key: 'SI', value: 'Sikkim' },
  { key: 'TN', value: 'Tamil Nadu' },
  { key: 'TR', value: 'Tripura' },
  { key: 'UP', value: 'Uttar Pradesh' },
  { key: 'UC', value: 'Uttaranchal' },
  { key: 'WB', value: 'West Bengal' },
  { key: 'DN', value: 'Dadra and Nagar Haveli' },
  { key: 'DD', value: 'Daman and Diu' }
];

export const COUNTRY_LIST = [
  { key: 'Afghanistan', value: 'Afghanistan' },
  { key: 'Aland Islands', value: 'Aland Islands' },
  { key: 'Albania', value: 'Albania' },
  { key: 'Algeria', value: 'Algeria' },
  { key: 'American Samoa', value: 'American Samoa' },
  { key: 'Andorra', value: 'Andorra' },
  { key: 'Angola', value: 'Angola' },
  { key: 'Anguilla', value: 'Anguilla' },
  { key: 'Antarctica', value: 'Antarctica' },
  { key: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { key: 'Argentina', value: 'Argentina' },
  { key: 'Armenia', value: 'Armenia' },
  { key: 'Aruba', value: 'Aruba' },
  { key: 'Australia', value: 'Australia' },
  { key: 'Austria', value: 'Austria' },
  { key: 'Azerbaijan', value: 'Azerbaijan' },
  { key: 'Bahamas', value: 'Bahamas' },
  { key: 'Bahrain', value: 'Bahrain' },
  { key: 'Bangladesh', value: 'Bangladesh' },
  { key: 'Barbados', value: 'Barbados' },
  { key: 'Belarus', value: 'Belarus' },
  { key: 'Belgium', value: 'Belgium' },
  { key: 'Belize', value: 'Belize' },
  { key: 'Benin', value: 'Benin' },
  { key: 'Bermuda', value: 'Bermuda' },
  { key: 'Bhutan', value: 'Bhutan' },
  { key: 'Bolivia', value: 'Bolivia' },
  { key: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { key: 'Botswana', value: 'Botswana' },
  { key: 'Bouvet Island', value: 'Bouvet Island' },
  { key: 'Brazil', value: 'Brazil' },
  { key: 'British Indian Ocean Territory', value: 'British Indian Ocean Territory' },
  { key: 'Brunei Darussalam', value: 'Brunei Darussalam' },
  { key: 'Bulgaria', value: 'Bulgaria' },
  { key: 'Burkina Faso', value: 'Burkina Faso' },
  { key: 'Burundi', value: 'Burundi' },
  { key: 'Cambodia', value: 'Cambodia' },
  { key: 'Cameroon', value: 'Cameroon' },
  { key: 'Canada', value: 'Canada' },
  { key: 'Cape Verde', value: 'Cape Verde' },
  { key: 'Cayman Islands', value: 'Cayman Islands' },
  { key: 'Central African Republic', value: 'Central African Republic' },
  { key: 'Chad', value: 'Chad' },
  { key: 'Chile', value: 'Chile' },
  { key: 'China', value: 'China' },
  { key: 'Christmas Island', value: 'Christmas Island' },
  { key: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
  { key: 'Colombia', value: 'Colombia' },
  { key: 'Comoros', value: 'Comoros' },
  { key: 'Congo', value: 'Congo' },
  { key: 'Congo, The Democratic Republic of The', value: 'Congo, The Democratic Republic of The' },
  { key: 'Cook Islands', value: 'Cook Islands' },
  { key: 'Costa Rica', value: 'Costa Rica' },
  { key: "Cote D'ivoire", value: "Cote D'ivoire" },
  { key: 'Croatia', value: 'Croatia' },
  { key: 'Cuba', value: 'Cuba' },
  { key: 'Cyprus', value: 'Cyprus' },
  { key: 'Czech Republic', value: 'Czech Republic' },
  { key: 'Denmark', value: 'Denmark' },
  { key: 'Djibouti', value: 'Djibouti' },
  { key: 'Dominica', value: 'Dominica' },
  { key: 'Dominican Republic', value: 'Dominican Republic' },
  { key: 'Ecuador', value: 'Ecuador' },
  { key: 'Egypt', value: 'Egypt' },
  { key: 'El Salvador', value: 'El Salvador' },
  { key: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { key: 'Eritrea', value: 'Eritrea' },
  { key: 'Estonia', value: 'Estonia' },
  { key: 'Ethiopia', value: 'Ethiopia' },
  { key: 'Falkland Islands (Malvinas)', value: 'Falkland Islands (Malvinas)' },
  { key: 'Faroe Islands', value: 'Faroe Islands' },
  { key: 'Fiji', value: 'Fiji' },
  { key: 'Finland', value: 'Finland' },
  { key: 'France', value: 'France' },
  { key: 'French Guiana', value: 'French Guiana' },
  { key: 'French Polynesia', value: 'French Polynesia' },
  { key: 'French Southern Territories', value: 'French Southern Territories' },
  { key: 'Gabon', value: 'Gabon' },
  { key: 'Gambia', value: 'Gambia' },
  { key: 'Georgia', value: 'Georgia' },
  { key: 'Germany', value: 'Germany' },
  { key: 'Ghana', value: 'Ghana' },
  { key: 'Gibraltar', value: 'Gibraltar' },
  { key: 'Greece', value: 'Greece' },
  { key: 'Greenland', value: 'Greenland' },
  { key: 'Grenada', value: 'Grenada' },
  { key: 'Guadeloupe', value: 'Guadeloupe' },
  { key: 'Guam', value: 'Guam' },
  { key: 'Guatemala', value: 'Guatemala' },
  { key: 'Guernsey', value: 'Guernsey' },
  { key: 'Guinea', value: 'Guinea' },
  { key: 'Guinea-bissau', value: 'Guinea-bissau' },
  { key: 'Guyana', value: 'Guyana' },
  { key: 'Haiti', value: 'Haiti' },
  { key: 'Heard Island and Mcdonald Islands', value: 'Heard Island and Mcdonald Islands' },
  { key: 'Holy See (Vatican City State)', value: 'Holy See (Vatican City State)' },
  { key: 'Honduras', value: 'Honduras' },
  { key: 'Hong Kong', value: 'Hong Kong' },
  { key: 'Hungary', value: 'Hungary' },
  { key: 'Iceland', value: 'Iceland' },
  { key: 'India', value: 'India' },
  { key: 'Indonesia', value: 'Indonesia' },
  { key: 'Iran, Islamic Republic of', value: 'Iran, Islamic Republic of' },
  { key: 'Iraq', value: 'Iraq' },
  { key: 'Ireland', value: 'Ireland' },
  { key: 'Isle of Man', value: 'Isle of Man' },
  { key: 'Israel', value: 'Israel' },
  { key: 'Italy', value: 'Italy' },
  { key: 'Jamaica', value: 'Jamaica' },
  { key: 'Japan', value: 'Japan' },
  { key: 'Jersey', value: 'Jersey' },
  { key: 'Jordan', value: 'Jordan' },
  { key: 'Kazakhstan', value: 'Kazakhstan' },
  { key: 'Kenya', value: 'Kenya' },
  { key: 'Kiribati', value: 'Kiribati' },
  { key: "Korea, Democratic People's Republic of", value: "Korea, Democratic People's Republic of" },
  { key: 'Korea, Republic of', value: 'Korea, Republic of' },
  { key: 'Kuwait', value: 'Kuwait' },
  { key: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { key: "Lao People's Democratic Republic", value: "Lao People's Democratic Republic" },
  { key: 'Latvia', value: 'Latvia' },
  { key: 'Lebanon', value: 'Lebanon' },
  { key: 'Lesotho', value: 'Lesotho' },
  { key: 'Liberia', value: 'Liberia' },
  { key: 'Libyan Arab Jamahiriya', value: 'Libyan Arab Jamahiriya' },
  { key: 'Liechtenstein', value: 'Liechtenstein' },
  { key: 'Lithuania', value: 'Lithuania' },
  { key: 'Luxembourg', value: 'Luxembourg' },
  { key: 'Macao', value: 'Macao' },
  { key: 'Macedonia, The Former Yugoslav Republic of', value: 'Macedonia, The Former Yugoslav Republic of' },
  { key: 'Madagascar', value: 'Madagascar' },
  { key: 'Malawi', value: 'Malawi' },
  { key: 'Malaysia', value: 'Malaysia' },
  { key: 'Maldives', value: 'Maldives' },
  { key: 'Mali', value: 'Mali' },
  { key: 'Malta', value: 'Malta' },
  { key: 'Marshall Islands', value: 'Marshall Islands' },
  { key: 'Martinique', value: 'Martinique' },
  { key: 'Mauritania', value: 'Mauritania' },
  { key: 'Mauritius', value: 'Mauritius' },
  { key: 'Mayotte', value: 'Mayotte' },
  { key: 'Mexico', value: 'Mexico' },
  { key: 'Micronesia, Federated States of', value: 'Micronesia, Federated States of' },
  { key: 'Moldova, Republic of', value: 'Moldova, Republic of' },
  { key: 'Monaco', value: 'Monaco' },
  { key: 'Mongolia', value: 'Mongolia' },
  { key: 'Montenegro', value: 'Montenegro' },
  { key: 'Montserrat', value: 'Montserrat' },
  { key: 'Morocco', value: 'Morocco' },
  { key: 'Mozambique', value: 'Mozambique' },
  { key: 'Myanmar', value: 'Myanmar' },
  { key: 'Namibia', value: 'Namibia' },
  { key: 'Nauru', value: 'Nauru' },
  { key: 'Nepal', value: 'Nepal' },
  { key: 'Netherlands', value: 'Netherlands' },
  { key: 'Netherlands Antilles', value: 'Netherlands Antilles' },
  { key: 'New Caledonia', value: 'New Caledonia' },
  { key: 'New Zealand', value: 'New Zealand' },
  { key: 'Nicaragua', value: 'Nicaragua' },
  { key: 'Niger', value: 'Niger' },
  { key: 'Nigeria', value: 'Nigeria' },
  { key: 'Niue', value: 'Niue' },
  { key: 'Norfolk Island', value: 'Norfolk Island' },
  { key: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
  { key: 'Norway', value: 'Norway' },
  { key: 'Oman', value: 'Oman' },
  { key: 'Pakistan', value: 'Pakistan' },
  { key: 'Palau', value: 'Palau' },
  { key: 'Palestinian Territory, Occupied', value: 'Palestinian Territory, Occupied' },
  { key: 'Panama', value: 'Panama' },
  { key: 'Papua New Guinea', value: 'Papua New Guinea' },
  { key: 'Paraguay', value: 'Paraguay' },
  { key: 'Peru', value: 'Peru' },
  { key: 'Philippines', value: 'Philippines' },
  { key: 'Pitcairn', value: 'Pitcairn' },
  { key: 'Poland', value: 'Poland' },
  { key: 'Portugal', value: 'Portugal' },
  { key: 'Puerto Rico', value: 'Puerto Rico' },
  { key: 'Qatar', value: 'Qatar' },
  { key: 'Reunion', value: 'Reunion' },
  { key: 'Romania', value: 'Romania' },
  { key: 'Russian Federation', value: 'Russian Federation' },
  { key: 'Rwanda', value: 'Rwanda' },
  { key: 'Saint Helena', value: 'Saint Helena' },
  { key: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { key: 'Saint Lucia', value: 'Saint Lucia' },
  { key: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon' },
  { key: 'Saint Vincent and The Grenadines', value: 'Saint Vincent and The Grenadines' },
  { key: 'Samoa', value: 'Samoa' },
  { key: 'San Marino', value: 'San Marino' },
  { key: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
  { key: 'Saudi Arabia', value: 'Saudi Arabia' },
  { key: 'Senegal', value: 'Senegal' },
  { key: 'Serbia', value: 'Serbia' },
  { key: 'Seychelles', value: 'Seychelles' },
  { key: 'Sierra Leone', value: 'Sierra Leone' },
  { key: 'Singapore', value: 'Singapore' },
  { key: 'Slovakia', value: 'Slovakia' },
  { key: 'Slovenia', value: 'Slovenia' },
  { key: 'Solomon Islands', value: 'Solomon Islands' },
  { key: 'Somalia', value: 'Somalia' },
  { key: 'South Africa', value: 'South Africa' },
  { key: 'South Georgia and The South Sandwich Islands', value: 'South Georgia and The South Sandwich Islands' },
  { key: 'Spain', value: 'Spain' },
  { key: 'Sri Lanka', value: 'Sri Lanka' },
  { key: 'Sudan', value: 'Sudan' },
  { key: 'Suriname', value: 'Suriname' },
  { key: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen' },
  { key: 'Swaziland', value: 'Swaziland' },
  { key: 'Sweden', value: 'Sweden' },
  { key: 'Switzerland', value: 'Switzerland' },
  { key: 'Syrian Arab Republic', value: 'Syrian Arab Republic' },
  { key: 'Taiwan', value: 'Taiwan' },
  { key: 'Tajikistan', value: 'Tajikistan' },
  { key: 'Tanzania, United Republic of', value: 'Tanzania, United Republic of' },
  { key: 'Thailand', value: 'Thailand' },
  { key: 'Timor-leste', value: 'Timor-leste' },
  { key: 'Togo', value: 'Togo' },
  { key: 'Tokelau', value: 'Tokelau' },
  { key: 'Tonga', value: 'Tonga' },
  { key: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { key: 'Tunisia', value: 'Tunisia' },
  { key: 'Turkey', value: 'Turkey' },
  { key: 'Turkmenistan', value: 'Turkmenistan' },
  { key: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
  { key: 'Tuvalu', value: 'Tuvalu' },
  { key: 'Uganda', value: 'Uganda' },
  { key: 'Ukraine', value: 'Ukraine' },
  { key: 'United Arab Emirates', value: 'United Arab Emirates' },
  { key: 'United Kingdom', value: 'United Kingdom' },
  { key: 'United States', value: 'United States' },
  { key: 'United States Minor Outlying Islands', value: 'United States Minor Outlying Islands' },
  { key: 'Uruguay', value: 'Uruguay' },
  { key: 'Uzbekistan', value: 'Uzbekistan' },
  { key: 'Vanuatu', value: 'Vanuatu' },
  { key: 'Venezuela', value: 'Venezuela' },
  { key: 'Viet Nam', value: 'Viet Nam' },
  { key: 'Virgin Islands, British', value: 'Virgin Islands, British' },
  { key: 'Virgin Islands, U.S.', value: 'Virgin Islands, U.S.' },
  { key: 'Wallis and Futuna', value: 'Wallis and Futuna' },
  { key: 'Western Sahara', value: 'Western Sahara' },
  { key: 'Yemen', value: 'Yemen' },
  { key: 'Zambia', value: 'Zambia' },
  { key: 'Zimbabwe', value: 'Zimbabwe' }
];

export const EMAIL_DECLARATION_OPTIONS = [
  { key: 'SE', value: 'SE - Self' },
  { key: 'SP', value: 'SP - Spouse' },
  { key: 'DC', value: 'DC - Dependent Children' },
  { key: 'DS', value: 'DS - Dependent Siblings' },
  { key: 'DP', value: 'DP - Dependent Parents' },
  { key: 'GD', value: 'GD - Guardian' },
  { key: 'PM', value: 'PM - PMS' },
  { key: 'CD', value: 'CD - Custodian' },
  { key: 'PO', value: 'PO – POA' }
];

export const MOBILE_DECLARATION_OPTIONS = [
  { key: 'SE', value: 'SE - Self' },
  { key: 'SP', value: 'SP - Spouse' },
  { key: 'DC', value: 'DC - Dependent Children' },
  { key: 'DS', value: 'DS - Dependent Siblings' },
  { key: 'DP', value: 'DP - Dependent Parents' },
  { key: 'GD', value: 'GD - Guardian' },
  { key: 'PM', value: 'PM - PMS' },
  { key: 'CD', value: 'CD - Custodian' },
  { key: 'PO', value: 'PO – POA' }
];

export const APPLICANT_COUNT_BY_HOLDING_PATTERN: { [key: string]: number } = {
  'SI': 1,
  'JO': 2,
  'AS': 3
};

export const OCCUPATION_LIST = [
  { key: '04', value: 'Agriculture' },
  { key: '01', value: 'Business' },
  { key: '06', value: 'Housewife' },
  { key: '03', value: 'Professional' },
  { key: '05', value: 'Retired' },
  { key: '02', value: 'Services' },
  { key: '07', value: 'Student' },
  { key: '41', value: 'Private Sector Service' },
  { key: '42', value: 'Public Sector/Government Service' },
  { key: '43', value: 'Forex Dealer' },
  { key: '09', value: 'Not Specified' },
  { key: '08', value: 'Others' }
];

export const REGISTRATION_TYPE_OPTIONS = [
  { label: 'New', value: 'New', disabled: false },
  { label: 'Mod', value: 'Mod', disabled: false },
  // { label: 'Nom', value: 'Nom', disabled: false },
];
