// Country list for dropdown (ISO 3166-1 alpha-3 code as key, country name as value)
export const COUNTRY_LIST: { key: string; value: string }[] = [
  { key: 'ABW', value: 'Aruba' },
  { key: 'AFG', value: 'Afghanistan' },
  { key: 'AGO', value: 'Angola' },
  { key: 'AIA', value: 'Anguilla' },
  { key: 'ALA', value: 'Åland Islands' },
  { key: 'ALB', value: 'Albania' },
  { key: 'AND', value: 'Andorra' },
  { key: 'ARE', value: 'United Arab Emirates' },
  { key: 'ARG', value: 'Argentina' },
  { key: 'ARM', value: 'Armenia' },
  { key: 'ASM', value: 'American Samoa' },
  { key: 'ATA', value: 'Antarctica' },
  { key: 'ATF', value: 'French Southern Territories' },
  { key: 'ATG', value: 'Antigua and Barbuda' },
  { key: 'AUS', value: 'Australia' },
  { key: 'AUT', value: 'Austria' },
  { key: 'AZE', value: 'Azerbaijan' },
  { key: 'BDI', value: 'Burundi' },
  { key: 'BEL', value: 'Belgium' },
  { key: 'BEN', value: 'Benin' },
  { key: 'BES', value: 'Bonaire, Sint Eustatius and Saba' },
  { key: 'BFA', value: 'Burkina Faso' },
  { key: 'BGD', value: 'Bangladesh' },
  { key: 'BGR', value: 'Bulgaria' },
  { key: 'BHR', value: 'Bahrain' },
  { key: 'BHS', value: 'Bahamas' },
  { key: 'BIH', value: 'Bosnia and Herzegovina' },
  { key: 'BLM', value: 'Saint Barthélemy' },
  { key: 'BLR', value: 'Belarus' },
  { key: 'BLZ', value: 'Belize' },
  { key: 'BMU', value: 'Bermuda' },
  { key: 'BOL', value: 'Bolivia, Plurinational State of' },
  { key: 'BRA', value: 'Brazil' },
  { key: 'BRB', value: 'Barbados' },
  { key: 'BRN', value: 'Brunei Darussalam' },
  { key: 'BTN', value: 'Bhutan' },
  { key: 'BVT', value: 'Bouvet Island' },
  { key: 'BWA', value: 'Botswana' },
  { key: 'CAF', value: 'Central African Republic' },
  { key: 'CAN', value: 'Canada' },
  { key: 'CCK', value: 'Cocos (Keeling) Islands' },
  { key: 'CHE', value: 'Switzerland' },
  { key: 'CHL', value: 'Chile' },
  { key: 'CHN', value: 'China' },
  { key: 'CIV', value: 'Côte d\'Ivoire' },
  { key: 'CMR', value: 'Cameroon' },
  { key: 'COD', value: 'Congo, Democratic Republic of the' },
  { key: 'COG', value: 'Congo' },
  { key: 'COK', value: 'Cook Islands' },
  { key: 'COL', value: 'Colombia' },
  { key: 'COM', value: 'Comoros' },
  { key: 'CPV', value: 'Cabo Verde' },
  { key: 'CRI', value: 'Costa Rica' },
  { key: 'CUB', value: 'Cuba' },
  { key: 'CUW', value: 'Curaçao' },
  { key: 'CXR', value: 'Christmas Island' },
  { key: 'CYM', value: 'Cayman Islands' },
  { key: 'CYP', value: 'Cyprus' },
  { key: 'CZE', value: 'Czechia' },
  { key: 'DEU', value: 'Germany' },
  { key: 'DJI', value: 'Djibouti' },
  { key: 'DMA', value: 'Dominica' },
  { key: 'DNK', value: 'Denmark' },
  { key: 'DOM', value: 'Dominican Republic' },
  { key: 'DZA', value: 'Algeria' },
  { key: 'ECU', value: 'Ecuador' },
  { key: 'EGY', value: 'Egypt' },
  { key: 'ERI', value: 'Eritrea' },
  { key: 'ESH', value: 'Western Sahara' },
  { key: 'ESP', value: 'Spain' },
  { key: 'EST', value: 'Estonia' },
  { key: 'ETH', value: 'Ethiopia' },
  { key: 'FIN', value: 'Finland' },
  { key: 'FJI', value: 'Fiji' },
  { key: 'FLK', value: 'Falkland Islands (Malvinas)' },
  { key: 'FRA', value: 'France' },
  { key: 'FRO', value: 'Faroe Islands' },
  { key: 'FSM', value: 'Micronesia, Federated States of' },
  { key: 'GAB', value: 'Gabon' },
  { key: 'GBR', value: 'United Kingdom of Great Britain and Northern Ireland' },
  { key: 'GEO', value: 'Georgia' },
  { key: 'GGY', value: 'Guernsey' },
  { key: 'GHA', value: 'Ghana' },
  { key: 'GIB', value: 'Gibraltar' },
  { key: 'GIN', value: 'Guinea' },
  { key: 'GLP', value: 'Guadeloupe' },
  { key: 'GMB', value: 'Gambia' },
  { key: 'GNB', value: 'Guinea-Bissau' },
  { key: 'GNQ', value: 'Equatorial Guinea' },
  { key: 'GRC', value: 'Greece' },
  { key: 'GRD', value: 'Grenada' },
  { key: 'GRL', value: 'Greenland' },
  { key: 'GTM', value: 'Guatemala' },
  { key: 'GUF', value: 'French Guiana' },
  { key: 'GUM', value: 'Guam' },
  { key: 'GUY', value: 'Guyana' },
  { key: 'HKG', value: 'Hong Kong' },
  { key: 'HMD', value: 'Heard Island and McDonald Islands' },
  { key: 'HND', value: 'Honduras' },
  { key: 'HRV', value: 'Croatia' },
  { key: 'HTI', value: 'Haiti' },
  { key: 'HUN', value: 'Hungary' },
  { key: 'IDN', value: 'Indonesia' },
  { key: 'IMN', value: 'Isle of Man' },
  { key: 'IND', value: 'India' },
  { key: 'IOT', value: 'British Indian Ocean Territory' },
  { key: 'IRL', value: 'Ireland' },
  { key: 'IRN', value: 'Iran, Islamic Republic of' },
  { key: 'IRQ', value: 'Iraq' },
  { key: 'ISL', value: 'Iceland' },
  { key: 'ISR', value: 'Israel' },
  { key: 'ITA', value: 'Italy' },
  { key: 'JAM', value: 'Jamaica' },
  { key: 'JEY', value: 'Jersey' },
  { key: 'JOR', value: 'Jordan' },
  { key: 'JPN', value: 'Japan' },
  { key: 'KAZ', value: 'Kazakhstan' },
  { key: 'KEN', value: 'Kenya' },
  { key: 'KGZ', value: 'Kyrgyzstan' },
  { key: 'KHM', value: 'Cambodia' },
  { key: 'KIR', value: 'Kiribati' },
  { key: 'KNA', value: 'Saint Kitts and Nevis' },
  { key: 'KOR', value: 'Korea, Republic of' },
  { key: 'KWT', value: 'Kuwait' },
  { key: 'LAO', value: 'Lao People\'s Democratic Republic' },
  { key: 'LBN', value: 'Lebanon' },
  { key: 'LBR', value: 'Liberia' },
  { key: 'LBY', value: 'Libya' },
  { key: 'LCA', value: 'Saint Lucia' },
  { key: 'LIE', value: 'Liechtenstein' },
  { key: 'LKA', value: 'Sri Lanka' },
  { key: 'LSO', value: 'Lesotho' },
  { key: 'LTU', value: 'Lithuania' },
  { key: 'LUX', value: 'Luxembourg' },
  { key: 'LVA', value: 'Latvia' },
  { key: 'MAC', value: 'Macao' },
  { key: 'MAF', value: 'Saint Martin (French part)' },
  { key: 'MAR', value: 'Morocco' },
  { key: 'MCO', value: 'Monaco' },
  { key: 'MDA', value: 'Moldova, Republic of' },
  { key: 'MDG', value: 'Madagascar' },
  { key: 'MDV', value: 'Maldives' },
  { key: 'MEX', value: 'Mexico' },
  { key: 'MHL', value: 'Marshall Islands' },
  { key: 'MKD', value: 'North Macedonia' },
  { key: 'MLI', value: 'Mali' },
  { key: 'MLT', value: 'Malta' },
  { key: 'MMR', value: 'Myanmar' },
  { key: 'MNE', value: 'Montenegro' },
  { key: 'MNG', value: 'Mongolia' },
  { key: 'MNP', value: 'Northern Mariana Islands' },
  { key: 'MOZ', value: 'Mozambique' },
  { key: 'MRT', value: 'Mauritania' },
  { key: 'MSR', value: 'Montserrat' },
  { key: 'MTQ', value: 'Martinique' },
  { key: 'MUS', value: 'Mauritius' },
  { key: 'MWI', value: 'Malawi' },
  { key: 'MYS', value: 'Malaysia' },
  { key: 'MYT', value: 'Mayotte' },
  { key: 'NAM', value: 'Namibia' },
  { key: 'NCL', value: 'New Caledonia' },
  { key: 'NER', value: 'Niger' },
  { key: 'NFK', value: 'Norfolk Island' },
  { key: 'NGA', value: 'Nigeria' },
  { key: 'NIC', value: 'Nicaragua' },
  { key: 'NIU', value: 'Niue' },
  { key: 'NLD', value: 'Netherlands, Kingdom of the' },
  { key: 'NOR', value: 'Norway' },
  { key: 'NPL', value: 'Nepal' },
  { key: 'NRU', value: 'Nauru' },
  { key: 'NZL', value: 'New Zealand' },
  { key: 'OMN', value: 'Oman' },
  { key: 'PAK', value: 'Pakistan' },
  { key: 'PAN', value: 'Panama' },
  { key: 'PCN', value: 'Pitcairn' },
  { key: 'PER', value: 'Peru' },
  { key: 'PHL', value: 'Philippines' },
  { key: 'PLW', value: 'Palau' },
  { key: 'PNG', value: 'Papua New Guinea' },
  { key: 'POL', value: 'Poland' },
  { key: 'PRI', value: 'Puerto Rico' },
  { key: 'PRK', value: 'Korea, Democratic People\'s Republic of' },
  { key: 'PRT', value: 'Portugal' },
  { key: 'PRY', value: 'Paraguay' },
  { key: 'PSE', value: 'Palestine, State of' },
  { key: 'PYF', value: 'French Polynesia' },
  { key: 'QAT', value: 'Qatar' },
  { key: 'REU', value: 'Réunion' },
  { key: 'ROU', value: 'Romania' },
  { key: 'RUS', value: 'Russian Federation' },
  { key: 'RWA', value: 'Rwanda' },
  { key: 'SAU', value: 'Saudi Arabia' },
  { key: 'SDN', value: 'Sudan' },
  { key: 'SEN', value: 'Senegal' },
  { key: 'SGP', value: 'Singapore' },
  { key: 'SGS', value: 'South Georgia and the South Sandwich Islands' },
  { key: 'SHN', value: 'Saint Helena, Ascension and Tristan da Cunha' },
  { key: 'SJM', value: 'Svalbard and Jan Mayen' },
  { key: 'SLB', value: 'Solomon Islands' },
  { key: 'SLE', value: 'Sierra Leone' },
  { key: 'SLV', value: 'El Salvador' },
  { key: 'SMR', value: 'San Marino' },
  { key: 'SOM', value: 'Somalia' },
  { key: 'SPM', value: 'Saint Pierre and Miquelon' },
  { key: 'SRB', value: 'Serbia' },
  { key: 'SSD', value: 'South Sudan' },
  { key: 'STP', value: 'Sao Tome and Principe' },
  { key: 'SUR', value: 'Suriname' },
  { key: 'SVK', value: 'Slovakia' },
  { key: 'SVN', value: 'Slovenia' },
  { key: 'SWE', value: 'Sweden' },
  { key: 'SWZ', value: 'Eswatini' },
  { key: 'SXM', value: 'Sint Maarten (Dutch part)' },
  { key: 'SYC', value: 'Seychelles' },
  { key: 'SYR', value: 'Syrian Arab Republic' },
  { key: 'TCA', value: 'Turks and Caicos Islands' },
  { key: 'TCD', value: 'Chad' },
  { key: 'TGO', value: 'Togo' },
  { key: 'THA', value: 'Thailand' },
  { key: 'TJK', value: 'Tajikistan' },
  { key: 'TKL', value: 'Tokelau' },
  { key: 'TKM', value: 'Turkmenistan' },
  { key: 'TLS', value: 'Timor-Leste' },
  { key: 'TON', value: 'Tonga' },
  { key: 'TTO', value: 'Trinidad and Tobago' },
  { key: 'TUN', value: 'Tunisia' },
  { key: 'TUR', value: 'Türkiye' },
  { key: 'TUV', value: 'Tuvalu' },
  { key: 'TWN', value: 'Taiwan, Province of China' },
  { key: 'TZA', value: 'Tanzania, United Republic of' },
  { key: 'UGA', value: 'Uganda' },
  { key: 'UKR', value: 'Ukraine' },
  { key: 'UMI', value: 'United States Minor Outlying Islands' },
  { key: 'URY', value: 'Uruguay' },
  { key: 'USA', value: 'United States of America' },
  { key: 'UZB', value: 'Uzbekistan' },
  { key: 'VAT', value: 'Holy See' },
  { key: 'VCT', value: 'Saint Vincent and the Grenadines' },
  { key: 'VEN', value: 'Venezuela, Bolivarian Republic of' },
  { key: 'VGB', value: 'Virgin Islands (British)' },
  { key: 'VIR', value: 'Virgin Islands (U.S.)' },
  { key: 'VNM', value: 'Viet Nam' },
  { key: 'VUT', value: 'Vanuatu' },
  { key: 'WLF', value: 'Wallis and Futuna' },
  { key: 'WSM', value: 'Samoa' },
  { key: 'YEM', value: 'Yemen' },
  { key: 'ZAF', value: 'South Africa' },
  { key: 'ZMB', value: 'Zambia' },
  { key: 'ZWE', value: 'Zimbabwe' }
];




export const COUNTRY_CODE_LIST: { key: string; value: string }[] = [
  { key: 'Afghanistan(+93)', value: '+93' },
  { key: 'Albania(+355)', value: '+355' },
  { key: 'Algeria(+213)', value: '+213' },
  { key: 'American Samoa(+1684)', value: '+1684' },
  { key: 'Andorra(+376)', value: '+376' },
  { key: 'Angola(+244)', value: '+244' },
  { key: 'Anguilla(+1264)', value: '+1264' },
  { key: 'Antigua and Barbuda(+1268)', value: '+1268' },
  { key: 'Argentina(+54)', value: '+54' },
  { key: 'Armenia(+374)', value: '+374' },
  { key: 'Aruba(+297)', value: '+297' },
  { key: 'Australia(+61)', value: '+61' },
  { key: 'Austria(+43)', value: '+43' },
  { key: 'Azerbaijan(+994)', value: '+994' },

  { key: 'Bahamas(+1242)', value: '+1242' },
  { key: 'Bahrain(+973)', value: '+973' },
  { key: 'Bangladesh(+880)', value: '+880' },
  { key: 'Barbados(+1246)', value: '+1246' },
  { key: 'Belarus(+375)', value: '+375' },
  { key: 'Belgium(+32)', value: '+32' },
  { key: 'Belize(+501)', value: '+501' },
  { key: 'Benin(+229)', value: '+229' },
  { key: 'Bermuda(+1441)', value: '+1441' },
  { key: 'Bhutan(+975)', value: '+975' },
  { key: 'Bolivia(+591)', value: '+591' },
  { key: 'Bosnia and Herzegovina(+387)', value: '+387' },
  { key: 'Botswana(+267)', value: '+267' },
  { key: 'Brazil(+55)', value: '+55' },
  { key: 'British Virgin Islands(+1284)', value: '+1284' },
  { key: 'Brunei(+673)', value: '+673' },
  { key: 'Bulgaria(+359)', value: '+359' },
  { key: 'Burkina Faso(+226)', value: '+226' },
  { key: 'Burundi(+257)', value: '+257' },

  { key: 'Cambodia(+855)', value: '+855' },
  { key: 'Cameroon(+237)', value: '+237' },
  { key: 'Canada(+1)', value: '+1' },
  { key: 'Cape Verde(+238)', value: '+238' },
  { key: 'Cayman Islands(+1345)', value: '+1345' },
  { key: 'Central African Republic(+236)', value: '+236' },
  { key: 'Chad(+235)', value: '+235' },
  { key: 'Chile(+56)', value: '+56' },
  { key: 'China(+86)', value: '+86' },
  { key: 'Colombia(+57)', value: '+57' },
  { key: 'Comoros(+269)', value: '+269' },
  { key: 'Congo(+242)', value: '+242' },
  { key: 'Costa Rica(+506)', value: '+506' },
  { key: 'Croatia(+385)', value: '+385' },
  { key: 'Cuba(+53)', value: '+53' },
  { key: 'Cyprus(+357)', value: '+357' },
  { key: 'Czech Republic(+420)', value: '+420' },

  { key: 'Denmark(+45)', value: '+45' },
  { key: 'Djibouti(+253)', value: '+253' },
  { key: 'Dominica(+1767)', value: '+1767' },
  { key: 'Dominican Republic(+1809)', value: '+1809' },

  { key: 'Ecuador(+593)', value: '+593' },
  { key: 'Egypt(+20)', value: '+20' },
  { key: 'El Salvador(+503)', value: '+503' },
  { key: 'Estonia(+372)', value: '+372' },
  { key: 'Ethiopia(+251)', value: '+251' },

  { key: 'Finland(+358)', value: '+358' },
  { key: 'France(+33)', value: '+33' },

  { key: 'Gabon(+241)', value: '+241' },
  { key: 'Gambia(+220)', value: '+220' },
  { key: 'Georgia(+995)', value: '+995' },
  { key: 'Germany(+49)', value: '+49' },
  { key: 'Ghana(+233)', value: '+233' },
  { key: 'Greece(+30)', value: '+30' },
  { key: 'Grenada(+1473)', value: '+1473' },
  { key: 'Guatemala(+502)', value: '+502' },
  { key: 'Guyana(+592)', value: '+592' },

  { key: 'Haiti(+509)', value: '+509' },
  { key: 'Honduras(+504)', value: '+504' },
  { key: 'Hong Kong(+852)', value: '+852' },
  { key: 'Hungary(+36)', value: '+36' },

  { key: 'Iceland(+354)', value: '+354' },
  { key: 'India(+91)', value: '+91' },
  { key: 'Indonesia(+62)', value: '+62' },
  { key: 'Iran(+98)', value: '+98' },
  { key: 'Iraq(+964)', value: '+964' },
  { key: 'Ireland(+353)', value: '+353' },
  { key: 'Israel(+972)', value: '+972' },
  { key: 'Italy(+39)', value: '+39' },

  { key: 'Jamaica(+1876)', value: '+1876' },
  { key: 'Japan(+81)', value: '+81' },
  { key: 'Jordan(+962)', value: '+962' },

  { key: 'Kazakhstan(+7)', value: '+7' },
  { key: 'Kenya(+254)', value: '+254' },
  { key: 'Kuwait(+965)', value: '+965' },

  { key: 'Laos(+856)', value: '+856' },
  { key: 'Latvia(+371)', value: '+371' },
  { key: 'Lebanon(+961)', value: '+961' },
  { key: 'Lesotho(+266)', value: '+266' },
  { key: 'Liberia(+231)', value: '+231' },
  { key: 'Libya(+218)', value: '+218' },
  { key: 'Lithuania(+370)', value: '+370' },
  { key: 'Luxembourg(+352)', value: '+352' },

  { key: 'Malaysia(+60)', value: '+60' },
  { key: 'Maldives(+960)', value: '+960' },
  { key: 'Mali(+223)', value: '+223' },
  { key: 'Malta(+356)', value: '+356' },
  { key: 'Mexico(+52)', value: '+52' },
  { key: 'Monaco(+377)', value: '+377' },
  { key: 'Mongolia(+976)', value: '+976' },
  { key: 'Montenegro(+382)', value: '+382' },
  { key: 'Morocco(+212)', value: '+212' },
  { key: 'Mozambique(+258)', value: '+258' },

  { key: 'Namibia(+264)', value: '+264' },
  { key: 'Nepal(+977)', value: '+977' },
  { key: 'Netherlands(+31)', value: '+31' },
  { key: 'New Zealand(+64)', value: '+64' },
  { key: 'Nicaragua(+505)', value: '+505' },
  { key: 'Nigeria(+234)', value: '+234' },
  { key: 'Norway(+47)', value: '+47' },

  { key: 'Oman(+968)', value: '+968' },

  { key: 'Pakistan(+92)', value: '+92' },
  { key: 'Panama(+507)', value: '+507' },
  { key: 'Paraguay(+595)', value: '+595' },
  { key: 'Peru(+51)', value: '+51' },
  { key: 'Philippines(+63)', value: '+63' },
  { key: 'Poland(+48)', value: '+48' },
  { key: 'Portugal(+351)', value: '+351' },

  { key: 'Qatar(+974)', value: '+974' },

  { key: 'Romania(+40)', value: '+40' },
  { key: 'Russia(+7)', value: '+7' },
  { key: 'Rwanda(+250)', value: '+250' },

  { key: 'Saudi Arabia(+966)', value: '+966' },
  { key: 'Senegal(+221)', value: '+221' },
  { key: 'Serbia(+381)', value: '+381' },
  { key: 'Singapore(+65)', value: '+65' },
  { key: 'Slovakia(+421)', value: '+421' },
  { key: 'Slovenia(+386)', value: '+386' },
  { key: 'Somalia(+252)', value: '+252' },
  { key: 'South Africa(+27)', value: '+27' },
  { key: 'South Korea(+82)', value: '+82' },
  { key: 'Spain(+34)', value: '+34' },
  { key: 'Sri Lanka(+94)', value: '+94' },
  { key: 'Sudan(+249)', value: '+249' },
  { key: 'Sweden(+46)', value: '+46' },
  { key: 'Switzerland(+41)', value: '+41' },
  { key: 'Syria(+963)', value: '+963' },

  { key: 'Taiwan(+886)', value: '+886' },
  { key: 'Thailand(+66)', value: '+66' },
  { key: 'Tunisia(+216)', value: '+216' },
  { key: 'Turkey(+90)', value: '+90' },

  { key: 'Uganda(+256)', value: '+256' },
  { key: 'Ukraine(+380)', value: '+380' },
  { key: 'United Arab Emirates(+971)', value: '+971' },
  { key: 'United Kingdom(+44)', value: '+44' },
  { key: 'United States(+1)', value: '+1' },
  { key: 'Uruguay(+598)', value: '+598' },

  { key: 'Venezuela(+58)', value: '+58' },
  { key: 'Vietnam(+84)', value: '+84' },

  { key: 'Yemen(+967)', value: '+967' },

  { key: 'Zambia(+260)', value: '+260' },
  { key: 'Zimbabwe(+263)', value: '+263' }
];

export const COUNTRY_TaxRes_LIST: { code: string; label: string }[] = [
  { code: 'ABW', label: 'Aruba' },
  { code: 'AFG', label: 'Afghanistan' },
  { code: 'AGO', label: 'Angola' },
  { code: 'AIA', label: 'Anguilla' },
  { code: 'ALA', label: 'Åland Islands' },
  { code: 'ALB', label: 'Albania' },
  { code: 'AND', label: 'Andorra' },
  { code: 'ARE', label: 'United Arab Emirates' },
  { code: 'ARG', label: 'Argentina' },
  { code: 'ARM', label: 'Armenia' },
  { code: 'ASM', label: 'American Samoa' },
  { code: 'ATA', label: 'Antarctica' },
  { code: 'ATF', label: 'French Southern Territories' },
  { code: 'ATG', label: 'Antigua and Barbuda' },
  { code: 'AUS', label: 'Australia' },
  { code: 'AUT', label: 'Austria' },
  { code: 'AZE', label: 'Azerbaijan' },
  { code: 'BDI', label: 'Burundi' },
  { code: 'BEL', label: 'Belgium' },
  { code: 'BEN', label: 'Benin' },
  { code: 'BES', label: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BFA', label: 'Burkina Faso' },
  { code: 'BGD', label: 'Bangladesh' },
  { code: 'BGR', label: 'Bulgaria' },
  { code: 'BHR', label: 'Bahrain' },
  { code: 'BHS', label: 'Bahamas' },
  { code: 'BIH', label: 'Bosnia and Herzegovina' },
  { code: 'BLM', label: 'Saint Barthélemy' },
  { code: 'BLR', label: 'Belarus' },
  { code: 'BLZ', label: 'Belize' },
  { code: 'BMU', label: 'Bermuda' },
  { code: 'BOL', label: 'Bolivia, Plurinational State of' },
  { code: 'BRA', label: 'Brazil' },
  { code: 'BRB', label: 'Barbados' },
  { code: 'BRN', label: 'Brunei Darussalam' },
  { code: 'BTN', label: 'Bhutan' },
  { code: 'BVT', label: 'Bouvet Island' },
  { code: 'BWA', label: 'Botswana' },
  { code: 'CAF', label: 'Central African Republic' },
  { code: 'CAN', label: 'Canada' },
  { code: 'CCK', label: 'Cocos (Keeling) Islands' },
  { code: 'CHE', label: 'Switzerland' },
  { code: 'CHL', label: 'Chile' },
  { code: 'CHN', label: 'China' },
  { code: 'CIV', label: 'Côte d\'Ivoire' },
  { code: 'CMR', label: 'Cameroon' },
  { code: 'COD', label: 'Congo, Democratic Republic of the' },
  { code: 'COG', label: 'Congo' },
  { code: 'COK', label: 'Cook Islands' },
  { code: 'COL', label: 'Colombia' },
  { code: 'COM', label: 'Comoros' },
  { code: 'CPV', label: 'Cabo Verde' },
  { code: 'CRI', label: 'Costa Rica' },
  { code: 'CUB', label: 'Cuba' },
  { code: 'CUW', label: 'Curaçao' },
  { code: 'CXR', label: 'Christmas Island' },
  { code: 'CYM', label: 'Cayman Islands' },
  { code: 'CYP', label: 'Cyprus' },
  { code: 'CZE', label: 'Czechia' },
  { code: 'DEU', label: 'Germany' },
  { code: 'DJI', label: 'Djibouti' },
  { code: 'DMA', label: 'Dominica' },
  { code: 'DNK', label: 'Denmark' },
  { code: 'DOM', label: 'Dominican Republic' },
  { code: 'DZA', label: 'Algeria' },
  { code: 'ECU', label: 'Ecuador' },
  { code: 'EGY', label: 'Egypt' },
  { code: 'ERI', label: 'Eritrea' },
  { code: 'ESH', label: 'Western Sahara' },
  { code: 'ESP', label: 'Spain' },
  { code: 'EST', label: 'Estonia' },
  { code: 'ETH', label: 'Ethiopia' },
  { code: 'FIN', label: 'Finland' },
  { code: 'FJI', label: 'Fiji' },
  { code: 'FLK', label: 'Falkland Islands (Malvinas)' },
  { code: 'FRA', label: 'France' },
  { code: 'FRO', label: 'Faroe Islands' },
  { code: 'FSM', label: 'Micronesia, Federated States of' },
  { code: 'GAB', label: 'Gabon' },
  { code: 'GBR', label: 'United Kingdom of Great Britain and Northern Ireland' },
  { code: 'GEO', label: 'Georgia' },
  { code: 'GGY', label: 'Guernsey' },
  { code: 'GHA', label: 'Ghana' },
  { code: 'GIB', label: 'Gibraltar' },
  { code: 'GIN', label: 'Guinea' },
  { code: 'GLP', label: 'Guadeloupe' },
  { code: 'GMB', label: 'Gambia' },
  { code: 'GNB', label: 'Guinea-Bissau' },
  { code: 'GNQ', label: 'Equatorial Guinea' },
  { code: 'GRC', label: 'Greece' },
  { code: 'GRD', label: 'Grenada' },
  { code: 'GRL', label: 'Greenland' },
  { code: 'GTM', label: 'Guatemala' },
  { code: 'GUF', label: 'French Guiana' },
  { code: 'GUM', label: 'Guam' },
  { code: 'GUY', label: 'Guyana' },
  { code: 'HKG', label: 'Hong Kong' },
  { code: 'HMD', label: 'Heard Island and McDonald Islands' },
  { code: 'HND', label: 'Honduras' },
  { code: 'HRV', label: 'Croatia' },
  { code: 'HTI', label: 'Haiti' },
  { code: 'HUN', label: 'Hungary' },
  { code: 'IDN', label: 'Indonesia' },
  { code: 'IMN', label: 'Isle of Man' },
  { code: 'IND', label: 'India' },
  { code: 'IOT', label: 'British Indian Ocean Territory' },
  { code: 'IRL', label: 'Ireland' },
  { code: 'IRN', label: 'Iran, Islamic Republic of' },
  { code: 'IRQ', label: 'Iraq' },
  { code: 'ISL', label: 'Iceland' },
  { code: 'ISR', label: 'Israel' },
  { code: 'ITA', label: 'Italy' },
  { code: 'JAM', label: 'Jamaica' },
  { code: 'JEY', label: 'Jersey' },
  { code: 'JOR', label: 'Jordan' },
  { code: 'JPN', label: 'Japan' },
  { code: 'KAZ', label: 'Kazakhstan' },
  { code: 'KEN', label: 'Kenya' },
  { code: 'KGZ', label: 'Kyrgyzstan' },
  { code: 'KHM', label: 'Cambodia' },
  { code: 'KIR', label: 'Kiribati' },
  { code: 'KNA', label: 'Saint Kitts and Nevis' },
  { code: 'KOR', label: 'Korea, Republic of' },
  { code: 'KWT', label: 'Kuwait' },
  { code: 'LAO', label: 'Lao People\'s Democratic Republic' },
  { code: 'LBN', label: 'Lebanon' },
  { code: 'LBR', label: 'Liberia' },
  { code: 'LBY', label: 'Libya' },
  { code: 'LCA', label: 'Saint Lucia' },
  { code: 'LIE', label: 'Liechtenstein' },
  { code: 'LKA', label: 'Sri Lanka' },
  { code: 'LSO', label: 'Lesotho' },
  { code: 'LTU', label: 'Lithuania' },
  { code: 'LUX', label: 'Luxembourg' },
  { code: 'LVA', label: 'Latvia' },
  { code: 'MAC', label: 'Macao' },
  { code: 'MAF', label: 'Saint Martin (French part)' },
  { code: 'MAR', label: 'Morocco' },
  { code: 'MCO', label: 'Monaco' },
  { code: 'MDA', label: 'Moldova, Republic of' },
  { code: 'MDG', label: 'Madagascar' },
  { code: 'MDV', label: 'Maldives' },
  { code: 'MEX', label: 'Mexico' },
  { code: 'MHL', label: 'Marshall Islands' },
  { code: 'MKD', label: 'North Macedonia' },
  { code: 'MLI', label: 'Mali' },
  { code: 'MLT', label: 'Malta' },
  { code: 'MMR', label: 'Myanmar' },
  { code: 'MNE', label: 'Montenegro' },
  { code: 'MNG', label: 'Mongolia' },
  { code: 'MNP', label: 'Northern Mariana Islands' },
  { code: 'MOZ', label: 'Mozambique' },
  { code: 'MRT', label: 'Mauritania' },
  { code: 'MSR', label: 'Montserrat' },
  { code: 'MTQ', label: 'Martinique' },
  { code: 'MUS', label: 'Mauritius' },
  { code: 'MWI', label: 'Malawi' },
  { code: 'MYS', label: 'Malaysia' },
  { code: 'MYT', label: 'Mayotte' },
  { code: 'NAM', label: 'Namibia' },
  { code: 'NCL', label: 'New Caledonia' },
  { code: 'NER', label: 'Niger' },
  { code: 'NFK', label: 'Norfolk Island' },
  { code: 'NGA', label: 'Nigeria' },
  { code: 'NIC', label: 'Nicaragua' },
  { code: 'NIU', label: 'Niue' },
  { code: 'NLD', label: 'Netherlands, Kingdom of the' },
  { code: 'NOR', label: 'Norway' },
  { code: 'NPL', label: 'Nepal' },
  { code: 'NRU', label: 'Nauru' },
  { code: 'NZL', label: 'New Zealand' },
  { code: 'OMN', label: 'Oman' },
  { code: 'PAK', label: 'Pakistan' },
  { code: 'PAN', label: 'Panama' },
  { code: 'PCN', label: 'Pitcairn' },
  { code: 'PER', label: 'Peru' },
  { code: 'PHL', label: 'Philippines' },
  { code: 'PLW', label: 'Palau' },
  { code: 'PNG', label: 'Papua New Guinea' },
  { code: 'POL', label: 'Poland' },
  { code: 'PRI', label: 'Puerto Rico' },
  { code: 'PRK', label: 'Korea, Democratic People\'s Republic of' },
  { code: 'PRT', label: 'Portugal' },
  { code: 'PRY', label: 'Paraguay' },
  { code: 'PSE', label: 'Palestine, State of' },
  { code: 'PYF', label: 'French Polynesia' },
  { code: 'QAT', label: 'Qatar' },
  { code: 'REU', label: 'Réunion' },
  { code: 'ROU', label: 'Romania' },
  { code: 'RUS', label: 'Russian Federation' },
  { code: 'RWA', label: 'Rwanda' },
  { code: 'SAU', label: 'Saudi Arabia' },
  { code: 'SDN', label: 'Sudan' },
  { code: 'SEN', label: 'Senegal' },
  { code: 'SGP', label: 'Singapore' },
  { code: 'SGS', label: 'South Georgia and the South Sandwich Islands' },
  { code: 'SHN', label: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'SJM', label: 'Svalbard and Jan Mayen' },
  { code: 'SLB', label: 'Solomon Islands' },
  { code: 'SLE', label: 'Sierra Leone' },
  { code: 'SLV', label: 'El Salvador' },
  { code: 'SMR', label: 'San Marino' },
  { code: 'SOM', label: 'Somalia' },
  { code: 'SPM', label: 'Saint Pierre and Miquelon' },
  { code: 'SRB', label: 'Serbia' },
  { code: 'SSD', label: 'South Sudan' },
  { code: 'STP', label: 'Sao Tome and Principe' },
  { code: 'SUR', label: 'Suriname' },
  { code: 'SVK', label: 'Slovakia' },
  { code: 'SVN', label: 'Slovenia' },
  { code: 'SWE', label: 'Sweden' },
  { code: 'SWZ', label: 'Eswatini' },
  { code: 'SXM', label: 'Sint Maarten (Dutch part)' },
  { code: 'SYC', label: 'Seychelles' },
  { code: 'SYR', label: 'Syrian Arab Republic' },
  { code: 'TCA', label: 'Turks and Caicos Islands' },
  { code: 'TCD', label: 'Chad' },
  { code: 'TGO', label: 'Togo' },
  { code: 'THA', label: 'Thailand' },
  { code: 'TJK', label: 'Tajikistan' },
  { code: 'TKL', label: 'Tokelau' },
  { code: 'TKM', label: 'Turkmenistan' },
  { code: 'TLS', label: 'Timor-Leste' },
  { code: 'TON', label: 'Tonga' },
  { code: 'TTO', label: 'Trinidad and Tobago' },
  { code: 'TUN', label: 'Tunisia' },
  { code: 'TUR', label: 'Türkiye' },
  { code: 'TUV', label: 'Tuvalu' },
  { code: 'TWN', label: 'Taiwan, Province of China' },
  { code: 'TZA', label: 'Tanzania, United Republic of' },
  { code: 'UGA', label: 'Uganda' },
  { code: 'UKR', label: 'Ukraine' },
  { code: 'UMI', label: 'United States Minor Outlying Islands' },
  { code: 'URY', label: 'Uruguay' },
  { code: 'USA', label: 'United States of America' },
  { code: 'UZB', label: 'Uzbekistan' },
  { code: 'VAT', label: 'Holy See' },
  { code: 'VCT', label: 'Saint Vincent and the Grenadines' },
  { code: 'VEN', label: 'Venezuela, Bolivarian Republic of' },
  { code: 'VGB', label: 'Virgin Islands (British)' },
  { code: 'VIR', label: 'Virgin Islands (U.S.)' },
  { code: 'VNM', label: 'Viet Nam' },
  { code: 'VUT', label: 'Vanuatu' },
  { code: 'WLF', label: 'Wallis and Futuna' },
  { code: 'WSM', label: 'Samoa' },
  { code: 'YEM', label: 'Yemen' },
  { code: 'ZAF', label: 'South Africa' },
  { code: 'ZMB', label: 'Zambia' },
  { code: 'ZWE', label: 'Zimbabwe' }
];